global proc FilePathLocator() {};

string $locatorInfo = `whatIs FilePathLocator`;
string $filePath = `substring $locatorInfo 25 999`;
string $pluginDirectory = `dirname $filePath`;

string $pythonCommand = "import sys;";
$pythonCommand += "sys.path.append('" + $pluginDirectory + "');";
$pythonCommand += "import install;";
$pythonCommand += "import importlib;";
$pythonCommand += "importlib.reload(install);";
$pythonCommand += "install.Install()";

python($pythonCommand);